#This is role 

- name: Assignment7-8
  hosts: all
  become: true
  gather_facts: true
  roles: 
    roles: 
    - role: MySQL_role
      tags:
        - MySQL

    - role: Java_role
      tags:
        - Java

    - role: tomcat_role
      tags:
        - Tomcat

    - role: nginx_role
      tags:
        - Nginx
