#This is role 

- name: Assignment7-8
  hosts: all
  become: true
  gather_facts: true
  roles: 
    - role: mysql-role
      tags:
        - MySql

    - role: myrole
      tags:
        - Java

    - role: tomcat-role
      tags:
        - Tomcat

    - role: nginx-role
      tags:
        - Nginx
