--
# tasks file for Assignment-8_ansible
- name: Installing MySQL
  apt: 
    name: mysql-server 
    state: latest
    update_cache: yes
  when: ansible_facts['os_family'] == 'Debian'
  notify: RestartMySQL

- name: Installing MySQL
  yum: 
     name: mysql-community-server
     state: present
     update_cache: yes
  when: ansible_facts['os_family'] == 'RedHat' 
  notify: RestartMySQL for Redhat machine
