---
# tasks file for tomact-role

- name: Installing Tomcat
  apt:
   name: tomcat9
   state: present
  when: ansible_facts['os_family'] == 'Debian'

- name: Installing tomcat
  yum:
   name: tomcat
   state: latest
  when: ansible_facts['os_family'] == 'RedHat'

- name: Starting tomcat
  service:
    name: tomcat.service
    state: restarted
  when: ansible_facts['os_family'] == 'RedHat'

- name: Starting tomcat
  service:
    name: tomcat9.service
    state: restarted
  when: ansible_facts['os_family'] == 'Debian'
