---
# tasks file for nginx-role
# tasks file for nginx_role
- name: Installing nginx
  apt: 
   name: nginx
   state: present
  when: ansible_facts['os_family'] == 'Debian'

- name: Installing nginx
  yum: 
   name: nginx
   state: present
  when: ansible_facts['os_family'] == 'RedHat'
  
- name: Starting nginx on Redhat
  service:
     name: nginx
     state: started
