---
# tasks file for myrole---
- name: Installing Java
  apt:
   name: openjdk-8-jdk
   state: present
  when: ansible_facts['os_family'] == 'Debian'

- name: Installing Java
  yum:
   name: java-1.8.0-openjdk
   state: present
  when: ansible_facts['os_family'] == 'RedHat'




...
